version: '3.1'

services:

  db:
    image: dbms_image
    restart: always
    container_name: dbms_container
    ports:
      - 3306:3306
    # volumes:
    #   - ./entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: e_store
      MYSQL_USER: nikitaAdd commentMore actions
      MYSQL_PASSWORD: biba
      MYSQL_ROOT_PASSWORD: person
      MYSQL_ROOT_HOST: '%'
    # command:
    #   - --character-set-server=utf8
    #   - --collation-server=utf8_general_ci
    # character-set-server:
    #   - utf8
    # (this is just an example, not intended to be a production configuration)