version: "3.1"

services:
  cdc:
    image: cdc_image
    restart: always
    container_name: cdc_container
    depends_on:
      - generator
    entrypoint: "bash -c \"sleep 30 && /app/build/Release/diplom\""

  generator:
    image: generator_image
    restart: always
    container_name: generator_container
    depends_on:
      - dbms

  dbms:
    image: dbms_image
    restart: always
    container_name: dbms_container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: e_store
      MYSQL_ROOT_PASSWORD: person
      MYSQL_ROOT_HOST: "%"
